### ISSUE TITLE
Small note on the instructions...

### ISSUE THREAD

**Issue by GollyJer** [pmndrs/eslint-plugin-valtio#15]
Noticed this when installing and though I'd let you know...

When you add `'plugin:valtio/recommended',` to the `extends` array it enables all the recommended rules from the plugin. Adding the rules directly (second step in the instructions) is redundant. Specific rule entries are only needed if you want to do something different than the recommended.

e.g. - user only wants `"valtio/avoid-this-in-proxy": ["warn"],` so they add that to the rules and do not add the recommended settings to `extend`.

**Comment by dai-shi** [comment]
> You can enable the rule to activate the plugin.

I think we mean something like this:
"Alternatively, you can enable rules in the plugin, selectively."

How does it sound?

**Comment by GollyJer** [comment]
That is good.👍
In my experience it's not clear for, many people, how `extends` and `rules` in eslint work. Making it clearer in instructions like this helps!
