### ISSUE TITLE
Adjust rule for Valtio v2

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/eslint-plugin-valtio#47]
In v2, the incompatibility with useMemo and so on will be resolved, https://github.com/pmndrs/valtio/pull/866
so, this plugin should avoid warning such usages with v2.

I wonder if there's a way in eslint to change the behavior based on Valtio versions. Otherwise, we can simply upgrade, which is reasonable for simplicity too.

@barelyhuman Can you work on it? It's not in a hurry.

**Comment by barelyhuman** [comment]
I'll check both options this weekend and implement accordingly

**Comment by barelyhuman** [comment]
Since the sandbox isn't working, any chance you can validate #48 locally?
Will merge post that

**Comment by dai-shi** [comment]
I don't think it's easy even with csb build. Let me review tests.

**Comment by barelyhuman** [comment]
https://github.com/pmndrs/eslint-plugin-valtio/releases/tag/v0.6.4
