### ISSUE TITLE
Support eslint v9 flat config

### ISSUE THREAD

**Issue by dzcpy** [pmndrs/eslint-plugin-valtio#50]

**Comment by z496090280** [comment]
![image](https://github.com/user-attachments/assets/27ebeea5-5c70-4b6f-8076-380ff40aeb7f)
Oops! Something went wrong! :(
"eslint": "^9.9.0",

**Comment by dai-shi** [comment]
Would anyone like to take this?

**Comment by dai-shi** [comment]
Nice. I don't know about v8 compatibility, but to be honest, I'm still on v8.

**Comment by barelyhuman** [comment]
I'll try to keep compat but if it doesn't work we'll just have to maintain 2 versions, cause I'm on v8 in most projects as well

**Comment by dai-shi** [comment]
Can anyone help testing #53?

**Comment by barelyhuman** [comment]
https://github.com/pmndrs/eslint-plugin-valtio/releases/tag/v0.7.0

Up
